### ISSUE TITLE
Compilation fails with -j2 and higher

### ISSUE THREAD

**Issue by anders-larsson** [acrisci/playerctl#21] opened 2015-10-07 17:41 UTC
Hello,

Build fails if more than one thread (job) is used during "make" phase. This is probably due to race conditions since it fails on different things if -j2 and -j3 is used.

I found this because I created an ebuild to merge playerctl on Gentoo (available here: https://github.com/anders-larsson/gentoo-overlay/tree/master/media-sound/playerctl).

From travis (https://travis-ci.org/anders-larsson/gentoo-overlay):
````
   media-sound/playerctl/playerctl-0.4.2.ebuild: Upstream parallel compilation bug (ebuild calls emake -j1 on line: 39)
   media-sound/playerctl/playerctl-9999.ebuild: Upstream parallel compilation bug (ebuild calls emake -j1 on line: 39)
````

Build log:
````
playerctl-0.4.2 % make -j2
make  all-recursive
make[1]: Entering directory '/mnt/local/storage/home/workarea/playerctl-0.4.2'
Making all in playerctl
make[2]: Entering directory '/mnt/local/storage/home/workarea/playerctl-0.4.2/playerctl'
make  all-am
make[3]: Entering directory '/mnt/local/storage/home/workarea/playerctl-0.4.2/playerctl'
  CC       playerctl-player.lo
  CC       playerctl-generated.lo
  CC       playerctl-playerctl-cli.o
  GISCAN   Playerctl_1_0_gir
libtool:   error: cannot find the library 'libplayerctl-1.0.la' or unhandled argument 'libplayerctl-1.0.la'
linking of temporary binary failed: Command '['/bin/sh', '../libtool', '--mode=link', '--tag=CC', '--silent', 'cc', '-o', '/mnt/local/storage/home/workarea/playerctl-0.4.2/playerctl/tmp-introspectHf69RB/Playerctl-Playerctl_1_0_gir', '-export-dynamic', '/mnt/local/storage/home/workarea/playerctl-0.4.2/playerctl/tmp-introspectHf69RB/Playerctl-Playerctl_1_0_gir.o', '-L.', 'libplayerctl-1.0.la', '-lgio-2.0', '-lgobject-2.0', '-Wl,--export-dynamic', '-lgmodule-2.0', '-pthread', '-lglib-2.0']' returned non-zero exit status 1
/usr/share/gobject-introspection-1.0/Makefile.introspection:153: recipe for target 'Playerctl_1_0_gir' failed
make[3]: *** [Playerctl_1_0_gir] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/mnt/local/storage/home/workarea/playerctl-0.4.2/playerctl'
Makefile:424: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/mnt/local/storage/home/workarea/playerctl-0.4.2/playerctl'
Makefile:438: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/mnt/local/storage/home/workarea/playerctl-0.4.2'
Makefile:370: recipe for target 'all' failed
make: *** [all] Error 2
````

**Comment by acrisci** [comment] 2015-10-18 21:13
This is caused by the generated code with `gdubs-codegen`. Maybe I should not be generating that code during compilation, but add it to the repo instead.

**Comment by acrisci** [comment] 2015-10-18 22:58
duplicate of #11

**Closed by acrisci** 2015-10-18 22:58 UTC
