### ISSUE TITLE
playerctl volume, status and metadata not working with Spotify on Arch Linux

### ISSUE THREAD

**Issue by grubersjoe** [acrisci/playerctl#20] opened 2015-10-06 08:30 UTC
Hey,

I'm using Arch Linux and want to control Spotify v1.0.14 (latest release) with playerctl. The following commands work as expected:

* play
* pause
* play-pause
* stop
* next
* previous

Unfortunately the others however seem to be broken right now:

* volume: has no effect at all
* status: prints "Not available"
* metadata: has no effect at all

Is this a problem of the Spotify client? Apparently DBUS support was removed in Spotify and was [reintegrated just recently with v1.0.13](https://community.spotify.com/t5/Help-Desktop-Linux-Windows-Web/1-01-1062-DBus-interface-gone/td-p/1121946). Are they maybe lacking some features of MPRIS in their current implementation?

**Comment by acrisci** [comment] 2015-10-07 00:58
I can confirm there is an issue with metadata and playerctl. Volume is probably not our issue because that didn't work before. Status I can't confirm, but probably a playerctl issue.

I will look into it when I can.

**Comment by freundTech** [comment] 2015-10-10 15:41
Also not working on my system. Spotify version 1.0.15.

Entering `dbus-send --print-reply --session --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'` in the Terminal returns the correct metadata.

`playerctl metadata` returns nothing.

**Comment by NiclasEriksen** [comment] 2015-10-13 00:36
Not working here either, player is found and can be controlled, but returns no metadata/status/volume. Running version 1.0.15 on Arch x64.

**Comment by freundTech** [comment] 2015-10-13 15:49
I had a closer look at the problem (Wasn't able to fix it).

All dbus methods seem to work without problems.
Properties don't work. The current Spotify version has only implemented the 'Metadata' property, so volume and status not working is a problem on spotifys side.

The metadata problem really confuses me. Getting metadata using dbus-send works without problems, but getting it with playerctl doesn't work.
On the other hand getting metadata using playerctl works on both the old spotify version (Pre 1.0) and vlc.

**Comment by acrisci** [comment] 2015-10-18 22:14
It looks like the generated function `org_mpris_media_player2_player_get_metadata()` is failing to return a value for the metadata property for spotify.

When I subscribe to the signal change, I get no metadata and this warning:

    GLib-GIO-WARNING **: Value for PropertiesChanged signal with type '(sa{sv}an)' does not match '(sa{sv}as)'

So maybe they are not setting the metadata property correctly according to the spec.

**Comment by acrisci** [comment] 2015-10-18 22:41
The generated function seems to be relying on some kind of cache.
 
It's calling `g_dbus_proxy_get_cached_property ()` which returns

> A reference to the GVariant instance that holds the value for property_name or NULL if the value is not in the cache. The returned reference must be freed with g_variant_unref().

Perhaps the new spotify dbus implementation does not use this cache.

Using `g_dbus_proxy_call_sync ()` seems to work ok, such as with this `dbus-send` command.

> dbus-send --session --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:"org.mpris.MediaPlayer2.Player" string:"Metadata"

I will try this as a workaround.

**Comment by acrisci** [comment] 2015-10-18 23:27
Unfortunately, getting Volume or PlaybackStatus in a similar way to this causes a hang. You can observe a similar hang in d-feet when trying to get these properties.

This is a bug in spotify that we cannot work around.

**Comment by acrisci** [comment] 2015-10-18 23:48
Pushed first change to make getting metadata with cli work. Please test.

Next I have to make the event work properly.

**Comment by NiclasEriksen** [comment] 2015-10-19 01:31
The change seems to be working, here's what playerctl metadata returns:

    {'mpris:trackid': <'spotify:track:6PVuMhSlLOt7QHhIkNyvii'>, 'mpris:length': <uint64 340861000>, 'mpris:artUrl': <'https://open.spotify.com/image/7beb4b315cce43b86d7d5225d7c0a11200d1454a'>, 'xesam:album': <'Memory'>, 'xesam:albumArtist': <['Tom Misch']>, 'xesam:artist': <['Tom Misch']>, 'xesam:autoRating': <0.5>, 'xesam:discNumber': <1>, 'xesam:title': <'Memory'>, 'xesam:trackNumber': <1>, 'xesam:url': <'https://open.spotify.com/track/6PVuMhSlLOt7QHhIkNyvii'>}%

**Comment by grubersjoe** [comment] 2015-10-19 07:04
Thanks for the workaround. It's working here again as well:

```
{'mpris:trackid': <'spotify:track:0DtY5J5GFyB7gI8xQAFdhS'>, 'mpris:length': <uint64 290000000>, 'mpris:artUrl': <'https://open.spotify.com/image/12d31963f64336f334667e30ccc2857b85a38a83'>, 'xesam:album': <'Sadnecessary'>, 'xesam:albumArtist': <['Milky Chance']>, 'xesam:artist': <['Milky Chance']>, 'xesam:autoRating': <0.5>, 'xesam:discNumber': <1>, 'xesam:title': <'Stunner'>, 'xesam:trackNumber': <1>, 'xesam:url': <'https://open.spotify.com/track/0DtY5J5GFyB7gI8xQAFdhS'>}
```

**Comment by Cauterize-Linux** [comment] 2015-11-22 14:55
Thank you. Great Job guys. Was driving me crazy trying to get this to work. I figured it was just me.

**Comment by acrisci** [comment] 2015-11-22 17:51
I can get the event to work, but it will be really hard. I've been putting it off hoping for a dot release from spotify to fix their dbus interface. Will work on it soon and then release.

**Comment by milouse** [comment] 2015-11-24 09:27
I've found a workaround to get spotify playing status in simple case. This is not intended to be included in playerctl, but I think it can help you in your scripts until upstream fix of dbus status properties by spotify.

I just watch for running status of my pulseaudio sink inputs. If I have spotify running and no sink inputs running, I conclude that spotify is in Paused state, otherwise it should be in Playing state.

Something like this (I already know I've a running spotify instance before executing this check):

    TOTALCOUNT=$(pacmd list-sink-inputs | grep -c index)
    SINKCOUNT=$(pacmd list-sink-inputs | grep -c 'state: RUNNING')
    if [ $TOTALCOUNT -gt 1 ]; then
        # It seems there is several player register, maybe spotify + a youtube video or else
        MPRISSTATUS=unknown
    elif [ $SINKCOUNT = 1 ]; then
        MPRISSTATUS=Playing
    else
        MPRISSTATUS=Paused
     fi

If it can help...

**Comment by t3zla** [comment] 2015-12-07 03:28
Is status working yet?

**Comment by acrisci** [comment] 2015-12-07 04:44
I don't believe status can possibly work. Go complain to spotify.

**Comment by psamim** [comment] 2016-02-01 09:46
I confirm that I have this problem using Spotify 1.0.19.106-3 on Archlinux and Playerctl 0.4.2-1

**Comment by t3zla** [comment] 2016-02-01 15:33
@psamim Since you are on arch you can use the spotify-stable package from the AUR. That version of spotify (0.9.17-4) works and is what I am using with no problems.

**Comment by acrisci** [comment] 2016-02-02 01:06
I'm going to prepare a release with my fix soon even though the event still doesn't work.

**Comment by theilgaard** [comment] 2016-02-05 18:53
@t3zla  No cigar, not getting any status from playerctl. I'm using arch and using that specific package from AUR.

**Comment by mckennajones** [comment] 2016-02-10 05:26
I hate to ask, but could anyone quickly explain how to implement the fix for the metadata on my own?

**Comment by acrisci** [comment] 2016-02-10 22:37
@mckennajones are you talking about the cli fix or the library fix?

**Comment by mckennajones** [comment] 2016-02-11 06:12
@acrisci Just the cli fix. I'm trying to use the metadata command for a status bar on i3 window manager.

**Comment by acrisci** [comment] 2016-03-20 16:56
I'm releasing without metadata event support so I'm closing this. See #26 for the issue of metadata event support.

**Closed by acrisci** 2016-03-20 16:56 UTC

**Comment by in1t3r** [comment] 2018-03-05 10:09
I run on this same issue is the seeking the position available now with spotify and volume change as they do not work for me on Debian

**Comment by freundTech** [comment] 2018-03-05 21:38
That's not a problem with playerctl, but with Spotify. Spotify only implements a part of mpris2.

Directly sending the relevant messages using dbus-send also doesn't do anything and when trying to read the volume and position attributes from Spotify they always return 0.

**Comment by fm-dev-mx** [comment] 2022-07-06 14:10
If somebody have yet the same problem, in /usr/share/kbd/keymaps/

	touch personal.map  	(create the file) 

	Paste this...

	  XF86AudioMute 'XF86AudioMute'
	  XF86AudioNext 'XF86AudioNext'
	  XF86AudioPlay 'XF86AudioPlay'
	  XF86AudioPrev 'XF86AudioPrev'
	  XF86AudioLowerVolume 'XF86AudioLowerVolume'
	  XF86AudioRaiseVolume 'XF86AudioRaiseVolume'
	  XF86Search 'XF86Search'
	  XF86Sleep 'XF86Sleep'      
	  XF86Lock 'XF86Lock' 


	localectl set-keymap --no-convert personal    (whithout the extension)

** The name of the file is not important, bur the directory must been  /usr/share/kbd/keymaps/ 


this work for me...

**Comment by flipsi** [comment] 2022-09-04 10:46
> XF86AudioMute 'XF86AudioMute'
>   XF86AudioNext 'XF86AudioNext'
>   XF86AudioPlay 'XF86AudioPlay'
>   XF86AudioPrev 'XF86AudioPrev'
>   XF86AudioLowerVolume 'XF86AudioLowerVolume'
>   XF86AudioRaiseVolume 'XF86AudioRaiseVolume'
>   XF86Search 'XF86Search'
>   XF86Sleep 'XF86Sleep'      
>   XF86Lock 'XF86Lock'

Thanks for the attempt. It doesn't work for me, unfortunately.

**Comment by flipsi** [comment] 2022-09-04 10:46
> If somebody have yet the same problem, in /usr/share/kbd/keymaps/
> 
> ```
> touch personal.map  	(create the file) 
> 
> Paste this...
> 
>   XF86AudioMute 'XF86AudioMute'
>   XF86AudioNext 'XF86AudioNext'
>   XF86AudioPlay 'XF86AudioPlay'
>   XF86AudioPrev 'XF86AudioPrev'
>   XF86AudioLowerVolume 'XF86AudioLowerVolume'
>   XF86AudioRaiseVolume 'XF86AudioRaiseVolume'
>   XF86Search 'XF86Search'
>   XF86Sleep 'XF86Sleep'      
>   XF86Lock 'XF86Lock' 
> 
> 
> localectl set-keymap --no-convert personal    (whithout the extension)
> ```
> 
> ** The name of the file is not important, bur the directory must been /usr/share/kbd/keymaps/
> 
> this work for me...

Thanks for the attempt. It doesn't work for me, unfortunately.
